accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:username>/follow/', views.follow, name='follow'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#  이 부분이 insta의 맨 아래쪽 MEDIA_URL 과 MEDIA_ROOR 에 연동해준다.
#  settings.MEDIA_URL 이쪽으로 오면 데이터는 document_root=settings.MEDIA_ROOT 에 있어 라는 의미.

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/like/', views.like, name='like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.
class User(AbstractUser):
    profile_image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='profile',
    )
    # post_set = 
    # like_posts =

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False) # self는 user을 넣는것과 같다.
    # followers =

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='image/%Y/%m'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user_id 가 자동으로 생성
    # 어떤 유저가 게시글을 작성했는지 확인하는 부분
    # AUTH_USER_MODEL가 대문자로 만 쓰여있는 있유는 상수(변하지 않는 데이터)라는 것을 의미 

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')


class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    # 1 대 N 관계
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        # 유지 보수를 위해서는 아래보다는 위에 코드가 관리하기 편하다.
        # model = User
        fields = ('username', 'profile_image', )


class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        exclude = ('user', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
#from .models import User # user를 불러오는데 아래 코드가 더 좋다 why?
# from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST) # request.POST -> id/pw 정보
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)


def profile(request, username):
    User = get_user_model()

    user_info = User.objects.get(username=username)

    context = {
        'user_info': user_info,
    }

    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, username):
    User = get_user_model() # get_user_model()로 user를 불러와서 User에 넣는다.
    
    me = request.user # 지금 로그인한 사람
    you = User.objects.get(username=username)

    # 팔로잉이 이미 되어있는 경우
    # if me in you.follows.all():
    if you in me.following.all():
        me.following.remove(you)

    # 팔로일이 아직 안되어 있는 경우
    else:
        me.following.add(you)

    return redirect('accounts:profile', username=username)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form': comment_form,
    }

    return render(request, 'index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)


@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)

        # 현재 로그인 유저
        comment.user = request.user
        # post_id를 기준으로 찾은 post
        post = Post.objects.get(id=post_id)
        comment.post = post

        comment.save()

        return redirect('posts:index')

@login_required 
def like(request, post_id):

    # 좋아요 버튼을 누른 유저 -> 지금 로그인되어 있는 사람
    user = request.user
    post = Post.objects.get(id=post_id)
 
 
    # 이미 좋아요 버튼을 누른 경우
    
    # if user in post.like_users.all() :
    if post in user.like_posts.all() :
        post.like_users.remove(user)
        # user.like_posts.remove(post)
        

    # 좋아요 버튼을 아직 안 누른 경우
    else:
        post.like_users.add(user)
        # user.like_posts.add(post)



    return redirect('posts:index')

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<h1>signup</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">

    </form>

    
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}

<div class="row">
    <div class="col-4">
        <img src="{{user_info.profile_image.url}}" alt="" class="img-fluid rounded-circle">
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-3">{{user_info.username}}</div>
            
            {% if user != user_info %}
            <!-- user는  지금 로그인한 사람  user_info 프로필페이지에 접속한 유저 -->
            <div class="col-4">
                {% if user in user_info.followers.all %}
                <!-- {% if user_info in user_info.followers.all %} -->
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-primary btn-sm">팔로우</a></div>
                {% elds %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-secondary btn-sm">팔로우</a></div>
                {% endif %}
            </div>
            {% endif %}
        <div class="row">
            <div class="col">게시물 {{user_info.post_set.all|length}} </div>
            <div class="col">팔로워 {{user_info.followers.all|length}} </div>
            <!-- accounts/models.py의 following 와 연결 -->
            <div class="col">팔로우 {{user_info.following.all|length}} </div>
        </div>
    </div>
</div>

<div class="row row-cols-3">

    {% for post in user_info.post_set.all %}
        <div class="col">
            <div class="card">
                <img src="{{post.image.url}}" alt="">
            </div>
        </div>

    {% endfor %}

</div>    

{% endblock %}

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        {% bootstrap_form %}
        <input type="submit">
    </form>
    
{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}
    
    {% for post in posts %}
        {% include '_card.html' %}
    {% endfor %}
    
{% endblock %}

templates/_card.html
{% load bootstrap5 %}
<div class="card mt-4">
    <div class="card-header">
        <p>
            <img src="{{post.user.profile_image.url}}" alt="" class="rounded-circle" width="50px">
            <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
        </p>
    </div>
    <img src="{{post.image.url}}" alt="...">
    <div class="card-body">

        <h5 class="card-title"></h5>
        <a href="{% url 'posts:like' post_id=post.id %}">
            {% if post in user.like_posts.all %}
                <i class="bi bi-balloon-heart-fill" style="color: blue"></i> 
            {% else %}
                <i class="bi bi-balloon-heart-"></i>
            {% endif %}
        </a> {{post.like_users.all|length}} 명이 좋아합니다.

        <p class="card-text">{{post.content}}</p>
        <p class="card-text">{{post.created_at|timesince}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
    <div class="card-footer">
        {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
            <!-- post_id는 변수명 post.id 객체 -->
            {% csrf_token %}
            {% bootstrap_form comment_form%}
            <input type="submit">
        </form>
        <hr>
        {% endif %}


        {% for comment in post.comment_set.all %}
            <li>{{comment.user}} : {{comment.content}}</li>
        {% endfor %}
    </div>

</div>

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-link "  href="{% url 'posts:create' %}">Create</a>
                <a class="nav-link " href="{% url 'accounts:profile' username=user %}">{{user}}</a>
            {% else %}
                <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
          
        </div>
      </div>
    </div>
  </nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

    {% include '_nav.html' %}


    <div class="container">
        {% block body %}
        {% endblock %}

    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>